### ISSUE TITLE
countours error

### ISSUE THREAD

**Issue by zelon88** [vipul-sharma20/document-scanner#4]
Hello,

I get the following error with valid arguments and (to the best of my knowledge) satisfied dependencies. Any ideas?

Traceback (most recent call last):
  File "/var/www/html/HRProprietary/HRCloud2/DATA/1/DOCSCAN.py", line 28, in <module>
    (contours, _) = cv2.findContours(edged, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
ValueError: too many values to unpack

Thank you!
zelon88

**Comment by vipul-sharma20** [comment]
Hi,

It maybe because of the OpenCV library version 3.x. AFAIK in OpenCV 2.4.x, `findContours` returns only 2 values but in later versions (3+) it returns 3 values `image, contours, hierarchy`.

So just replace `(contours, _)` with `image, contours, hierarchy = cv2.findContours(...)` and it should work fine.

Thanks

**Comment by zelon88** [comment]
That seems to work like a charm! Thanks so much, but now I appear to be getting another error. Sorry for being so new with Python!
Here's my error. I think I may have installed the wrong module to satisfy the rect dependency on line 3 of scanner.py.
Traceback (most recent call last):
  File "/var/www/html/HRProprietary/HRCloud2/DATA/1/DOCSCAN.py", line 45, in <module>
    approx = rect.rectify(target)
AttributeError: 'module' object has no attribute 'rectify'

**Comment by shahnawaj5488** [comment]
Hi Vipul,
Getting the same error
 AttributeError: 'module' object has no attribute 'rectify'
Using default python 2.7 which comes with ubuntu 14.04

**Comment by ZeroZipZilch** [comment]
The repository has a second file called rect.py that you need to add to your project directory

**Comment by 2017develper** [comment]
i have this error  on windows 10 can you help me please 
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\projects\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp, line 3492
Traceback (most recent call last):
  File "scanner.py", line 12, in <module>
    image = cv2.resize(image, (1500, 880))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize
